# only manual
trigger: none
pr: none

parameters:
  - name: 'DEV'
    displayName: 'Run on DEV environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'UAT'
    displayName: 'Run on UAT environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'PROD'
    displayName: 'Run on PROD environment'
    type: boolean
    default: True
    values:
      - False
      - True

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/heads/expose-output-tfplanapply # refs/tags/v6.19.0
      endpoint: "io-azure-devops-github-ro"

variables:
  TIME_OUT: 15
  # working dir
  WORKING_DIR: 'src/client-certs'
  DOMAIN_NAME: client_certs

stages:
  #DEV
  - ${{ if eq(parameters['DEV'], true) }}:
    - template: './base-deploy-pipelines.yml'
      parameters:
        ENV: 'dev_auto'
        ENV_FOLDER: 'dev'
        WORKING_DIR_MODULE: ${{ variables.WORKING_DIR }}
        DEFINITION_NAME: ${{ variables.DOMAIN_NAME }}
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_DEV)'
        SC_APPLY_NAME: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_DEV)'
        POOL_NAME: '$(TF_POOL_NAME_DEV)'
        PUBLISH_CREATED_ADDRESSES: true
        PUBLISH_OUTPUT: 'client_certificates_key_vaults'
    - template: './templates/client-certs-new-cert-mail.yml'
      parameters:
        ENV: 'dev_auto'
        DEFINITION_NAME: ${{ variables.DOMAIN_NAME }}
        POOL_NAME: '$(TF_POOL_NAME_DEV)'
        SC_NAME: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_DEV)'
        CA_KEY_VAULT_NAME: 'pagopa-d-weu-core-ca-kv'
  #UAT
  - ${{ if eq(parameters['UAT'], true) }}:
    - template: './base-deploy-pipelines.yml'
      parameters:
        ENV: 'uat_auto'
        ENV_FOLDER: 'uat'
        WORKING_DIR_MODULE: ${{ variables.WORKING_DIR }}
        DEFINITION_NAME: ${{ variables.DOMAIN_NAME }}
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_UAT)'
        SC_APPLY_NAME: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_UAT)'
        POOL_NAME: '$(TF_POOL_NAME_UAT)'
        PUBLISH_CREATED_ADDRESSES: true
        PUBLISH_OUTPUT: 'client_certificates_key_vaults'
    - template: './templates/client-certs-new-cert-mail.yml'
      parameters:
        ENV: 'uat_auto'
        DEFINITION_NAME: ${{ variables.DOMAIN_NAME }}
        POOL_NAME: '$(TF_POOL_NAME_UAT)'
        SC_NAME: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_UAT)'
        CA_KEY_VAULT_NAME: 'pagopa-u-weu-core-ca-kv'
  #PROD
  - ${{ if eq(parameters['PROD'], true) }}:
    - template: './base-deploy-pipelines.yml'
      parameters:
        ENV: 'prod_auto'
        ENV_FOLDER: 'prod'
        WORKING_DIR_MODULE: ${{ variables.WORKING_DIR }}
        DEFINITION_NAME: ${{ variables.DOMAIN_NAME }}
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_PROD)'
        SC_APPLY_NAME: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_PROD)'
        POOL_NAME: '$(TF_POOL_NAME_PROD)'
        PUBLISH_CREATED_ADDRESSES: true
        PUBLISH_OUTPUT: 'client_certificates_key_vaults'
    - template: './templates/client-certs-new-cert-mail.yml'
      parameters:
        ENV: 'prod_auto'
        DEFINITION_NAME: ${{ variables.DOMAIN_NAME }}
        POOL_NAME: '$(TF_POOL_NAME_PROD)'
        SC_NAME: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_PROD)'
        CA_KEY_VAULT_NAME: 'pagopa-p-weu-core-ca-kv'
